resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/AmadlaOrg/hery/cache:
    interfaces:
      ICache:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCache"
          inpackage: True
  github.com/AmadlaOrg/hery/cache/database:
    interfaces:
      IDatabase:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCacheDatabase"
          inpackage: True
      ISqlDb:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockSqlDb"
      ISqlTx:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockSqlTx"
  github.com/AmadlaOrg/hery/cache/parser:
    interfaces:
      IParser:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCacheParser"
          inpackage: True
  github.com/AmadlaOrg/hery/client:
    interfaces:
      IClient:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockClient"
          inpackage: True
  github.com/AmadlaOrg/hery/collection:
    interfaces:
      ICollection:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCollection"
          inpackage: True
      ICollectionEntity:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockCollectionEntity"
          inpackage: True
  github.com/AmadlaOrg/hery/entity:
    interfaces:
      IEntity:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntity"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/build:
    interfaces:
      IBuild:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityBuild"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/cmd/util:
    interfaces:
      IBuild:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityCmdUtil"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/get:
    interfaces:
      IGet:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityGet"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/schema:
    interfaces:
      ISchema:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntitySchema"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/schema/validation:
    interfaces:
      IValidation:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntitySchemaValidation"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/validation:
    interfaces:
      IValidation:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityValidation"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/version:
    interfaces:
      IVersion:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityVersion"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/version/validation:
    interfaces:
      IValidation:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntityVersionValidation"
          inpackage: True
  github.com/AmadlaOrg/hery/util/git:
    interfaces:
      IGit:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockUtilGit"
          inpackage: True
  github.com/AmadlaOrg/hery/util/git/remote:
    interfaces:
      IRemote:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockUtilGitRemote"
          inpackage: True
  github.com/AmadlaOrg/hery/storage:
    interfaces:
      IStorage:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockStorage"
          inpackage: True
  github.com/AmadlaOrg/hery/util/file:
    interfaces:
      IFile:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: MockFile
          inpackage: True
  sync:
    interfaces:
      Locker:
        config:
          dir: cache/database
          mockName: MockSyncLocker
          inpackage: False
          outpkg: database
  io/fs:
    interfaces:
      FileInfo:
        config:
          dir: util/file
          mockName: MockFileInfo
          inpackage: False
          outpkg: file
