with-expecter: True
packages:
  github.com/AmadlaOrg/hery/entity:
    interfaces:
      IEntity:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntity"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/build:
    interfaces:
      IBuild:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockBuild"
          inpackage: True
  github.com/AmadlaOrg/hery/entity/version:
    interfaces:
      IVersion:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockVersion"
          inpackage: True
  github.com/AmadlaOrg/hery/util/file:
    interfaces:
      File:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockFile"
          inpackage: True
  github.com/AmadlaOrg/hery/util/git:
    interfaces:
      RepoManager:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGit"
          inpackage: True
  github.com/AmadlaOrg/hery/util/git/remote:
    interfaces:
      RepoRemoteManager:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockGitRemote"
          inpackage: True
  github.com/AmadlaOrg/hery/util/json:
    interfaces:
      Json:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockJson"
          inpackage: True
  github.com/AmadlaOrg/hery/util/json/schema:
    interfaces:
      Schema:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockJsonSchema"
          inpackage: True
  github.com/AmadlaOrg/hery/util/yaml:
    interfaces:
      Yaml:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockYaml"
          inpackage: True
  github.com/AmadlaOrg/hery/storage:
    interfaces:
      IStorage:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockStorage"
          inpackage: True
